### ISSUE TITLE
Parking suspension table display in mobile view

### ISSUE THREAD

**Issue by 5jt** [hillsider-admins/hillsider-admins.github.io#20]
Too wide. Possible fixes?

![Screenshot 2021-10-01 at 08 45 45](https://user-images.githubusercontent.com/5923162/135584180-b4212a27-0d78-4a02-a004-c08af25c34a6.png)

**Comment by 5jt** [comment]
A better display for mobile – and for desktop as well?

---
**Parliament Hill**
* 1-5 Nov – Outside 17-25 inclusive
* 1-5 Nov – Outside 18-20 inclusive

**South Hill Park**
* 5 Nov – Outside number 112-144 inclusive

**Tanza Road**
* 7 Nov – Eight consecutive spaces between 15 and 23, as shown on map below
* 7 Nov – Outside 4 to 12 inclusive
* 8 Nov – Nine consecutive spaces from outside number 15 to outside number 23, as shown on map below
* 8 Nov – Nine consecutive spaces from 2 to 12, as shown on map below
* 12 Nov – Outside number 6

**Comment by 5jt** [comment]
Something like this?

![Screenshot 2021-11-13 at 16 11 41](https://user-images.githubusercontent.com/5923162/141650898-0537ac67-9121-417e-b73e-d9ad57f55530.png)

**Comment by 5jt** [comment]
Closed by commit 98344f839f97e6ab7dd951e3b2b50902ec827d2b

**Comment by aaaashy** [comment]
the separation of the streets seems a good idea for clarification, lets try it

**Comment by ghost** [comment]
![Screenshot 2022-01-04 at 15 29 37](https://user-images.githubusercontent.com/20816256/148082896-cb748b24-62ea-4076-8d81-21a89c26f0d1.png)

Result looks good. Code should be refactored to drop table.

**Comment by StephenTaylor-Kx** [comment]
Pushed to branch `issue20` (and to webserver) a fix for error that was dropping suspension from last street if there was only one. 

Leave issue open until now-redundant code removed from `parking-es6.js`.

**Comment by 5jt** [comment]
Pushed to branch `issue20` (and to webserver) a fix for error that was dropping suspension from last street if there was only one. 

Leave issue open and branch unmerged until now-redundant code removed from `parking-es6.js`.
